language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - 'travis_retry composer self-update'
  - 'travis_retry composer install --no-interaction --prefer-source --dev -o'
  - 'wget https://scrutinizer-ci.com/ocular.phar'
  - 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - 'phpenv rehash'

script:
  - 'mkdir -p build/logs'
  - 'php vendor/bin/phpunit -c phpunit.xml.dist'

after_script:
  - 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php vendor/bin/coveralls -v; fi;'
  - 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then export CODECLIMATE_REPO_TOKEN=c885c52095c8ce924d4ddb51a33b919d2af6e09c73b916857a99327c0bb79f08; php vendor/bin/test-reporter --stdout > codeclimate.json; fi;'
  - 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then curl -X POST -d @codeclimate.json -H "Content-Type: application/json" -H "User-Agent: Code Climate (PHP Test Reporter v0.1.1)" https://codeclimate.com/test_reports; fi;'
  - 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'

notifications:
  email:
    - 'ryan@ryanparman.com'
